---
name: Build

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        run:  echo "test test" > build.txt

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build.txt

  release:
    name: Release
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts

    - name: Print all github context
      run: |
          echo "Printing github.event context:"
          echo "${{ toJson(github) }}"

    - name: test
      run: |
        cat build.txt

    - name: release
      run: |
        echo "RELEASE!"
