---
name: Build

on:
  push:
    branches:
    - '*'
    tags:
    - '*'
  pull_request:
    branches:
    - '*'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Build
        run:  echo "test test" > build.txt