---
name: Tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: pytests
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && contains(github.event.ref, '/tags/')  # Only runs if the original event was a tag
  
    steps:

    - name: Fetch build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: test
      run: |
        cat build.txt

    - name: release
      run: |
        echo "RELEASE!"