---
name: Tests

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
    branches:
      - "*"
  pull_request:
    branches:
    - '*'


defaults:
  run:
    shell: bash

jobs:
  tests:
    name: pytests
    runs-on: ubuntu-22.04
    steps:

    - name: Fetch build artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: build-artifacts

    - name: test
      run: |
        cat build.txt
